# COM424 Lab Exercises

## 1. Introduction to Numpy

In [2]:
import numpy as np

In [3]:
print("Numpy version : ", np.__version__)

Numpy version :  1.26.4


In [7]:
a = list()
print("Variable a has type ")
print(type(a))
a = 2
print("Variable a has type ")
print(type(a))

Variable a has type 
<class 'list'>
Variable a has type 
<class 'int'>


In [8]:
a = np.array([1,2,3,4,5])


In [10]:
type(a)
print("Data type of numpy array a is ", a.dtype)

Data type of numpy array a is  int32


In [11]:
b = [1,'a',3.0, type(a)]
print(b)

[1, 'a', 3.0, <class 'numpy.ndarray'>]


In [12]:
c = np.array(b)
print("Contents of numpy array c are ", c)

Contents of numpy array c are  [1 'a' 3.0 <class 'numpy.ndarray'>]


In [13]:
print("Data type of numpy array c is ", c.dtype)

Data type of numpy array c is  object


In [16]:
d = np.array([1,2,3.0,4,6.8], dtype='float')
d

array([1. , 2. , 3. , 4. , 6.8])

In [20]:
e = np.random.randn(3)
e

array([ 0.33985267, -1.10276825, -0.06476172])

A set of evenly spaced numbers

In [21]:
f = np.linspace(0,10,5)
f

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

An array with an incremental range of numbers

In [23]:
z = np.arange(0,100) # Similar to Python's range function (start, end, step)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [28]:
print("Z's shape is ", z.shape)
print("Z's size is ", z.size)

Z's shape is  (100,)
Z's size is  100


In [39]:
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Create a multidimensional array from the array `z`

In [37]:
z_2d = z.reshape(25,4)
print(z_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]
 [64 65 66 67]
 [68 69 70 71]
 [72 73 74 75]
 [76 77 78 79]
 [80 81 82 83]
 [84 85 86 87]
 [88 89 90 91]
 [92 93 94 95]
 [96 97 98 99]]


In [41]:
z_2d.shape

(25, 4)

Create a `25 x 4` multidimensional array from the array `z_2d`

In [42]:
z_25x4 = z_2d.reshape(4,25)
z_25x4.shape

(4, 25)

In [48]:
z_reshaped = z_2d.reshape(4,-1)
z_reshaped.shape

(4, 25)

In [45]:
z_trans = z_2d.T
z_trans.shape

(4, 25)